version: "3.8"

services:
  postgres:
    container_name: "postgres"
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
    ports:
      - "5432:5432"
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
  memcached_1:
    container_name: "memcached_1"
    image: memcached
    ports:
      - '11211:11211'